# Generated by Django 2.0.2 on 2018-02-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='transactions',
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='balance.Balance'),
        ),
    ]
