# Generated by Django 2.0.2 on 2018-02-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_auto_20180215_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
