# Generated by Django 2.0.2 on 2018-02-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0007_transaction_transaction_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_balance',
            new_name='currentTotal',
        ),
    ]
