# Generated by Django 2.0.2 on 2018-02-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0009_auto_20180221_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currentTotal',
        ),
    ]
