# Generated by Django 2.0.2 on 2018-02-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0010_remove_transaction_currenttotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currentTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
